### ISSUE TITLE
The topic /joint_states is empty. I cannot get the dual robot arms position through get_current_state().

### ISSUE THREAD

**Issue by guningquan** [UniversalRobots/Universal_Robots_ROS_Tutorials#10]
Hi, thanks for your tutorials. I can bring up my two ur5 robot arms simultaneously.
And, I created my dual_ur5_moveit_config (ros1 melodic), connecting the config package to the real robots successfully.
But, I cannot get the positions of the bob arm and alice arm. The error is `Failed to fetch current robot state.`
The reason is that the bringup method of the Tutorials published `/bob/joint_states` and `/alice/joint_states` topics respectively.
But `moveit_commander.move_group.MoveGroupCommander.get_current_state()` is to get the position from topic `/joint_states`.
I input `rostopic echo /joint_states`, the output is empty.
Then I remap the topic `rosrun topic_tools relay alice/joint_states joint_states`. But this way only allows me to get the alice arm position correctly. 
Why the topic of `/joint_states` is empty?
Or, How can I get the correct positions of the two arms simultaneously without remap?

**Comment by VinDp** [comment]
Hi  @guningquan, 

sorry for the late reply, to solve your problem you can simply use 2 relays:
- `rosrun topic_tools relay alice/joint_states joint_states`
-  `rosrun topic_tools relay bob/joint_states joint_states`
 
In this way you should have the joint states of both robots on `/joint_states`.

**Comment by VinDp** [comment]
Hey @guningquan , I will close the issue since some time has passed. Feel free to reopen if still relevant.
