### ISSUE TITLE
Second robot not usable

### ISSUE THREAD

**Issue by ttmg1998** [UniversalRobots/Universal_Robots_ROS_Tutorials#13]
Hello everyone,

I try to run the example but everytime the visualization in rviz looks like in the picture.
Sometimes the bob is usable and the alice is not visbile and not controlable and sometimes the other way araound.
In the rqt_joint_trajectory_controller window I can also see and choose just one of the robots.
I already changed the port from 50005 to 60002 for the external control in the polyscope enviroment.
Thanks for your help!

![Bildschirmfoto vom 2023-12-14 11-08-06](https://github.com/UniversalRobots/Universal_Robots_ROS_Tutorials/assets/144101198/66d400b1-3172-4724-ba4f-0cd83f6c2e97)

**Comment by fmauch** [comment]
I'm sorry, I cannot reproduce your problem. Indeed, the port configuration for alice is wrong, I'll make a PR for that.

But apart from that, the two robots spawn flawlessly for me and are usable once I change alice's custom port from 50005 to 60002

**Comment by ttmg1998** [comment]
Hello fmauch,

sorry I forgot to post my solution here. I already solved the problem. I needed two different launch-files in dual_robot_startup.launch. Alice and Bob can't have the same file ur_control.launch. For that reason I created a second launch-file in the same folder. Anyway thank you for your help!
